services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employeedb
    ports:
      - "5432:5432"
    networks:
      - pipeline_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  spark-master:
    image: apache/spark:3.4.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    command: /opt/spark/sbin/start-master.sh
    ports:
      - "9090:8080"   # Use 9090 on the host to avoid conflicts with other services
      - "7077:7077"
    networks:
      - pipeline_network
    volumes:
      - ./data:/opt/spark/data
      - ./spark:/opt/spark/jobs

  spark-worker:
    image: apache/spark:3.4.1
    container_name: spark-worker
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    networks:
      - pipeline_network
    volumes:
      - ./data:/opt/spark/data
      - ./spark:/opt/spark/jobs

  spark-submit:
    image: apache/spark:3.4.1
    container_name: spark-submit
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for Spark master and PostgreSQL...' &&
      sleep 20 &&
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      --packages org.postgresql:postgresql:42.6.0
      /opt/spark/jobs/etl_job.py
      "
    depends_on:
      - spark-master
      - spark-worker
      - postgres
    networks:
      - pipeline_network
    volumes:
      - ./data:/opt/spark/data
      - ./spark:/opt/spark/jobs

networks:
  pipeline_network:
    driver: bridge

volumes:
  postgres_data:
