services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employeedb
    ports:
      - "5432:5432"
    networks:
      - pipeline_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    command: bash -c "/opt/spark/sbin/start-master.sh && tail -f /opt/spark/logs/*"
    ports:
      - "9090:8080"   # Spark Master Web UI (host 9090 to avoid conflicts)
      - "7077:7077"
    networks:
      - pipeline_network
    volumes:
      - ./data:/opt/spark/data
      - ./spark:/opt/spark/jobs

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    command: bash -c "sleep 10 && /opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark/logs/*"
    environment:
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    networks:
      - pipeline_network
    volumes:
      - ./data:/opt/spark/data
      - ./spark:/opt/spark/jobs

  spark-submit:
    image: apache/spark:latest
    container_name: spark-submit
    environment:
      - HOME=/tmp
      - IVY_HOME=/tmp/.ivy2
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for Spark master and PostgreSQL...' &&
      sleep 20 &&
      echo 'Downloading PostgreSQL JDBC driver...' &&
      curl -o /tmp/postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.6.0.jar &&
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      --jars /tmp/postgresql.jar
      /opt/spark/jobs/etl_job.py
      "
    depends_on:
      - spark-master
      - spark-worker
      - postgres
    networks:
      - pipeline_network
    volumes:
      - ./data:/opt/spark/data
      - ./spark:/opt/spark/jobs

networks:
  pipeline_network:
    driver: bridge

volumes:
  postgres_data:
